daemon off;
error_log /dev/stderr info;
pid /tmp/nginx.pid;

events {
    worker_connections 1024;
}

http {
    access_log /dev/stdout;
    server {
        listen 9191;
        location / {
            return 200 'OK';
        }
    }
}
