[supervisord]
logfile=./supervisord.log
pidfile=./supervisord.pid
nodaemon=false

[unix_http_server]
file=./supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix://./supervisor.sock

[program:dummy_loop]
command=bash -c "while true; do echo \"Tick $(date)\"; sleep 2; done"
stdout_logfile=./dummy_loop.log
stderr_logfile=./dummy_loop.err
autostart=false
autorestart=true
