#!/usr/bin/env sh

trap '' USR2          # ignore USR2; default Term is overridden

graceful_shutdown() {
    echo "PID: $$ | USR1 signal received. Performing cleanup..."
    echo "PID: $$ | Exiting gracefully."
    sleep 5
    exit 0
}

trap graceful_shutdown USR1

echo "PID: $$ | Script is running. Send USR1 to shut down."

while true; do
    sleep 1
done
