programs:
  nginx:
    cmd: '/usr/bin/nginx -p . -c configs/nginx/nginx.conf -e /dev/stderr -g "pid /tmp/nginx.pid;"'
    numprocs: 1
    umask: 022
    workingdir: /tmp
    autostart: true
    autorestart: unexpected
    exitcodes:
      - 0
      - 2
    startretries: 3
    starttime: 5
    stopsignal: TERM
    stoptime: 10
    stdout: /tmp/nginx.stdout
    stderr: /tmp/nginx.stderr
    env:
      STARTED_BY: taskmaster
      ANSWER: 42
  worker:
    cmd: '/usr/bin/sh -c ''while true; do echo "Process $(hostname) is working..."; sleep 5; done'''
    numprocs: 8
    umask: 077
    workingdir: /tmp
    autostart: true
    autorestart: unexpected
    exitcodes: [0]
    startretries: 3
    starttime: 5
    stopsignal: USR1
    stoptime: 10
    stdout: /tmp/worker.stdout
    stderr: /tmp/worker.stderr
