programs:
  alpha:
    cmd: "/usr/bin/sleep 60"
    numprocs: 1
    umask: 022
    workingdir: /tmp
    autostart: true
    autorestart: never
    exitcodes: [0]
    startretries: 3
    starttime: 1
    stopsignal: TERM
    stoptime: 2
    stdout: /tmp/taskmaster-alpha.out
    stderr: /tmp/taskmaster-alpha.err
  gamma:
    cmd: "/usr/bin/sleep 60"
    numprocs: 1
    umask: 022
    workingdir: /tmp
    autostart: true
    autorestart: never
    exitcodes: [0]
    startretries: 3
    starttime: 1
    stopsignal: TERM
    stoptime: 2
    stdout: /tmp/taskmaster-gamma.out
    stderr: /tmp/taskmaster-gamma.err
