programs:
  nginx:
    cmd: "nginx -p . -c ./apps/nginx/nginx.conf -e /dev/stderr"
    numprocs: 1
    umask: 022
    workingdir: .
    autostart: true
    autorestart: unexpected
    exitcodes:
      - 0
      - 2
    startretries: 3
    starttime: 5
    stopsignal: TERM
    stoptime: 10
    stdout: /tmp/nginx.stdout
    stderr: /tmp/nginx.stderr
  answer:
    cmd: "./apps/answer/run"
    numprocs: 8
    umask: 077
    workingdir: .
    autostart: true
    autorestart: unexpected
    exitcodes: [0]
    startretries: 3
    starttime: 5
    stopsignal: USR1
    stoptime: 10
    stdout: /tmp/answer.stdout
    stderr: /tmp/answer.stderr
    env:
      STARTED_BY: taskmaster
      ANSWER: 42
