programs:
  nginx:
    cmd: "nginx -p . -c ./apps/nginx/nginx.conf -e /dev/stderr"
    numprocs: 1
    umask: 022
    workingdir: .
    autostart: true
    autorestart: unexpected
    exitcodes:
      - 0
      - 2
    startretries: 3
    starttime: 5
    stopsignal: TERM
    stoptime: 10
    stdout: /tmp/nginx.stdout
    stderr: /tmp/nginx.stderr
  app:
    cmd: "./apps/answer/run"
    numprocs: 10
    umask: 000
    workingdir: .
    autostart: true
    autorestart: never
    exitcodes: [0]
    startretries: 2
    starttime: 2
    stopsignal: USR2
    stoptime: 10
    stdout: ./app.stdout
    stderr: ./app.stderr
    env:
      STARTED_BY: taskmaster
      ANSWER: 42
