programs:
  shortlived:
    cmd: "sleep 2"
    numprocs: 2
    umask: 022
    workingdir: /tmp
    autostart: true
    autorestart: never
    exitcodes:
      - 0
    startretries: 3
    starttime: 1
    stopsignal: TERM
    stoptime: 5
    stdout: /tmp/taskmaster-shortlived.out
    stderr: /tmp/taskmaster-shortlived.err
  echoer:
    cmd: "echo hello"
    numprocs: 1
    umask: 022
    workingdir: /tmp
    autostart: true
    autorestart: never
    exitcodes:
      - 0
    startretries: 3
    starttime: 1
    stopsignal: TERM
    stoptime: 5
    stdout: /tmp/taskmaster-echoer.out
    stderr: /tmp/taskmaster-echoer.err
    env:
      GREETING: hi
